const LEVELS: [&str; 51] = [
    "ai_showdown",
    "alu_1",
    "alu_2",
    "and_gate_3",
    "any_doubles",
    "binary_programming",
    "binary_search",
    "bit_adder",
    "bit_inverter",
    "byte_adder",
    "byte_constant",
    "byte_equal",
    "byte_less",
    "byte_less_i",
    "byte_mux",
    "byte_not",
    "byte_or",
    "byte_shift",
    "byte_xor",
    "capitalize",
    "circumference",
    "compute_xor",
    "conditions",
    "counting_signals",
    "dance",
    "decoder",
    "decoder1",
    "decoder3",
    "divide",
    "flood_predictor",
    "full_adder",
    "maze",
    "mod_4",
    "multiply",
    "not_gate",
    "odd_number_of_signals",
    "odd_ticks",
    "or_gate_3",
    "ram",
    "ram_component",
    "robot_racing",
    "saving_bytes",
    "saving_gracefully",
    "second_tick",
    "signed_negator",
    "sorter",
    "stack",
    "tick_tock",
    "tower",
    "xnor",
    "xor_gate",
];

pub fn handle() {
    println!("Available levels:");
    for level in LEVELS {
        println!("- {level}");
    }
}
